// The pinned canary public key (DESIGN 10). Committed as SOURCE because it is
// public information, and because being source is exactly what puts it under the
// reproducible build: an auditor who rebuilds the release confirms this pin, and a
// compelled operator who swaps it changes the release hash (which the rebuild+diff
// catches). The matching PRIVATE key is generated by the operator with
// tools/canary-keygen.mjs, held OFFLINE, and only ever used by tools/canary-sign.mjs.
//
// Empty until configured (off-until-key, the VAPID pattern): while empty the
// verifier reports `unconfigured`, a benign quiet state, never a false green. To
// rotate or recover from key loss, ship a release that empties this again (back to
// `unconfigured`) and then re-enable with a fresh key (DESIGN 10).
//
// Format: unpadded base64url of the 32-byte Ed25519 public key.
export const CANARY_PUBKEY_B64 = 'maqUME66MqP_iktKXcsCS38XjbsF7cwCB7aZ_gbovQE'
